# Generated by Django 4.1.7 on 2023-03-27 11:37

from django.db import migrations, models
import django_encryption.fields


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testmodel",
            name="enc_ssn_field",
            field=django_encryption.fields.EncryptedSSNField(null=True),
        ),
        migrations.AlterField(
            model_name="testmodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
