# Generated by Django 4.1.7 on 2023-03-19 12:47

from django.db import migrations, models
import django_encryption.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django_encryption.fields.EncryptedCharField()),
                ('email', django_encryption.fields.EncryptedEmailField()),
                ('phone', django_encryption.fields.EncryptedCharField()),
                ('address', django_encryption.fields.EncryptedCharField()),
                ('ssn', django_encryption.fields.EncryptedCharField()),
                ('dob', django_encryption.fields.EncryptedDateField()),
            ],
        ),
    ]
