name: Test orm-django
on:
  push:

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2

          - name: Setup Python
            uses: actions/setup-python@v2
            with:
              python-version: '3.10'

          - name: Install poetry
            run: |
              curl -sSL https://install.python-poetry.org | python3 -

          - name: Install dependencies
            run: cd orm-django && poetry install

          - name: Run vault
            run: |
              docker run --rm --init \
                     --name pvault-dev \
                     -p 8123:8123 \
                     -e PVAULT_SERVICE_LICENSE=${{ secrets.PVAULT_SERVICE_LICENSE }} \
                     -e PVAULT_SENTRY_ENABLE=true \
                     -e PVAULT_LOG_CUSTOMER_IDENTIFIER="piiano" \
                     -e PVAULT_LOG_CUSTOMER_ENV="SDK" \
                     -d \
                     piiano/pvault-dev:latest
              sleep 10
              # Runs vault with dev mode and set it a custom customer identifier/env for testing purposes. 

          - name: Test plugin
            run: |
              # we cant run poetry shell in this env so we need to run the tests with poetry run.
              # See discussion: https://github.com/python-poetry/poetry/discussions/3526

              cd orm-django && poetry run python3 manage.py test